<Project>
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <Company>OCI-Pool</Company>
    <Product>OCI-Pool</Product>
    <Version>1.0.0</Version>
    <Authors>OCI-Pool Contributors</Authors>
  </PropertyGroup>
</Project>
